### ISSUE TITLE
there is overlapping of texts in the login page of the application

### ISSUE THREAD

**Issue by darshan1328** [sanika391/SpoonShare#1] opened 2024-05-11 13:47 UTC
Can you assign me this as i will work in the direction of solving this problem by using better fonts and spacing and make the page more interactive

**Comment by sanika391** [comment] 2024-05-11 14:06
Sur. But just don't make any changes in the font.

**Comment by Shruti78** [comment] 2024-05-11 14:28
I want to work in solving this overlapping problem, Can u please assign me this issue.

**Comment by sanika391** [comment] 2024-05-11 14:33
Sure
Do mention yourself in the assignee section will assign you the issue.

**Comment by darshan1328** [comment] 2024-05-11 14:37
@sanika391 thank you..

**Comment by darshan1328** [comment] 2024-05-11 14:39
Dear Madam,
Can I get to know by what time should the issue be resolved?
Thank you
Darshan

**Comment by ascoder1109** [comment] 2024-05-12 09:43
@sanika391 Maam can you please assign me this issue? I have solved this problem

![spoon_share_login](https://github.com/sanika391/SpoonShare/assets/100013000/4deb2266-4bf2-4e22-95e6-3925bf8f28bb)


Also can I create a separate colors.dart file to store the colors?

**Comment by sanika391** [comment] 2024-05-14 12:35
[darshan1328](https://github.com/darshan1328)[darshan1328](https://github.com/darshan1328)[darshan1328](https://github.com/darshan1328)


I have assigned you the issue on first come first serve basis but now as seen so far you were inactive so I am assigning it to other people who have asked to contribute. But surely you can go ahead and work on it.

**Comment by T-Soni** [comment] 2024-05-16 11:15
Hii! I am a GSSoC'24 contributor. I would like to work on this issue and contribute to your project. Kindly assign it to me.

**Comment by sanika391** [comment] 2024-05-16 11:34
Hello....
Recently another Contributor has solved this issue. Is their anything from
your side? Like another issue you want to work upon or add any new feature.
You are welcome

**Comment by LEARNER-dakshesh** [comment] 2024-05-19 16:03
Hello @sanika391 can you please assign me this isssue. I wanted to work on issue.

**Comment by sanika391** [comment] 2024-05-19 16:28
Hello. Another Contributor has already solved this problem. Is their
anything else you want to work upon???

**Comment by T-Soni** [comment] 2024-05-21 08:01
Hello!
Thank you for assigning me the issue #1.
I got an email on May 16, 2024 stating that this issue has already been
resolved by another contributor. So, it would be kind of you if you could
confirm whether the issue is still open.

**Comment by sanika391** [comment] 2024-05-22 16:12
[T-Soni](https://github.com/T-Soni)
Thank you for your message.

I apologize for any confusion. The issue #1 has already been resolved by another contributor. I appreciate your willingness to help and your patience.

If there are any other issues or contributions you would like to work on, please let me know, and I would be happy to assign them to you.

Thank you for your understanding and support.

Best regards,
Sanika Chavan

**Closed** 2024-05-22 16:11 UTC
Labels: (gssoc), level2
