### ISSUE TITLE
🪲[Bug]: The mobile number , email, and links are not getting checked

### ISSUE THREAD

**Issue by a-m-a-nkumar** [sanika391/SpoonShare#26] opened 2024-05-16 01:58 UTC
**Describe the bug**
The mobile number , email, and links are not checked and any wrong value can be filled in those forms

**To Reproduce**
1. Go to Dashboard
2. Click on Become a Volunteer
3. Fill any values in mobile number , email address or links section.

**Expected behavior**
When a person enters wrong mobile number ( not a 10 digit number),then  it should identify it and report it to the user.The same goes for the links and  email address.

**Screenshots**
![WhatsApp Image 2024-05-16 at 07 26 08_5624e600](https://github.com/sanika391/SpoonShare/assets/99753046/5c6757c5-120c-4a50-ab1a-cc24c7ef49f2)

**Smartphone (please complete the following information):**
 - Device: Poco M2
 - OS: Andoid 11

**Comment by a-m-a-nkumar** [comment] 2024-05-16 02:08
I want to work on this issue.
I'm a GSSOC'24 contributor
I agree to follow this project's Code of Conduct

**Comment by sanika391** [comment] 2024-05-16 18:56
Sure!!! You can continue working on it.

**Comment by sanika391** [comment] 2024-05-16 18:57
Whenever you need any help just ping me here or via mail sanikachavan1806@gmail.com

**Comment by a-m-a-nkumar** [comment] 2024-05-17 12:35
I have created a pull request for the above mentioned issue @sanika391 .Please review.

**Comment by sanika391** [comment] 2024-05-20 15:08
Yes I have reviewed it and it looks good.
Well done! If you find any other issue then you can also go ahead with it. Great to connect with you......

**Comment by harsh6045** [comment] 2024-05-24 10:19
I am also interested in making changes on UI and improving the code quality. I am a GSSOC's 24 Contributor I have an experience in flutter. @sanika391

**Comment by sanika391** [comment] 2024-05-24 20:31
Hello @Harsh Langaliya,

Thank you for expressing your interest in contributing to the project. We
appreciate your enthusiasm and your experience with Flutter will definitely
be valuable to our efforts to improve the UI and code quality.

I look forward to your contributions and are excited to see how you can
help enhance the project. If you have any questions or need guidance, don't
hesitate to reach out.

Best regards,
Sanika Chavan
[https://www.linkedin.com/in/sanika-chavan-52457b236]

**Comment by harsh** [comment] 2024-05-24 20:52
You got the wrong Harsh. My handle is @harsh (the original) Harsh SabikhiSVP - RevenueOctopus Deploy4166165859On May 24, 2024, at 4:31 PM, Sanika ***@***.***> wrote:﻿
Hello @Harsh Langaliya,



Thank you for expressing your interest in contributing to the project. We

appreciate your enthusiasm and your experience with Flutter will definitely

be valuable to our efforts to improve the UI and code quality.



I look forward to your contributions and are excited to see how you can

help enhance the project. If you have any questions or need guidance, don't

hesitate to reach out.



Best regards,

Sanika Chavan

[https://www.linkedin.com/in/sanika-chavan-52457b236]



On Fri, May 24, 2024 at 3:50 PM Harsh Langaliya ***@***.***>

wrote:

**Comment by sanika391** [comment] 2024-05-24 20:56
[harsh6045](https://github.com/harsh6045)
I am extremely sorry for this

**Comment by harsh6045** [comment] 2024-05-25 00:17
Thank you for assigning me.

**Comment by CodewithAnn** [comment] 2024-06-09 10:21
Hey, I am a Gssoc contributor and would like to work on this bug. Can you please assign me this issue?

**Comment by sanika391** [comment] 2024-06-09 10:29
Hey @CodewithAnn,

Thanks for reaching out and expressing your interest in working on this bug. I'm happy to assign you this issue!
Feel free to ask if you have any questions or need further clarification. We're excited to see your contribution to improving our project!

Best,
Sanika Chavan
[https://www.linkedin.com/in/sanika-chavan-52457b236]

**Comment by CodewithAnn** [comment] 2024-06-09 11:13
Thank you @sanika391 for assigning this to me. Although this will be my first contribution to open source and GSSOC'24, I try to do my best to resolve this bug.

**Comment by sanika391** [comment] 2024-06-09 11:18
No problem, take your time.

**Comment by harsh** [comment] 2024-06-09 11:58
Wrong Harsh folks. Harsh SabikhiSVP - RevenueOctopus Deploy4166165859On Jun 9, 2024, at 7:18 AM, Sanika ***@***.***> wrote:﻿
No problem, take your time.

**Comment by vishalmaurya850** [comment] 2024-06-22 13:36
Can I have this issue @sanika391

**Comment by VITianLalit** [comment] 2024-06-23 08:24
I want to work on this issue pls assign it to me?

**Comment by sanika391** [comment] 2024-06-23 10:58
[VITianLalit](https://github.com/VITianLalit)

I've assigned the issue regarding the mobile number, email, and links not being checked to you. If you need any help, please feel free to contact me.

Thanks,
Sanika Chavan.
[https://www.linkedin.com/in/sanika-chavan-52457b236]

**Comment by VITianLalit** [comment] 2024-06-24 06:29
@sanika391 , I have made pull request pls review and merge it.

**Comment by vishalmaurya850** [comment] 2024-06-24 09:33
I don't think the issue is in the code @sanika391 @VITianLalit Please check for the bug in the app

**Comment by vishalmaurya850** [comment] 2024-06-24 09:36
The file volunteer_form.dart has no error maybe it's the issue of case sensitivity in the file.

**Comment by VITianLalit** [comment] 2024-06-25 15:22
@sanika391 , pls add the appropriate gssoc level.

**Comment by sanika391** [comment] 2024-06-25 15:27
Sure! You also do star the repository .

**Comment by vishalmaurya850** [comment] 2024-07-05 03:13
If issue solved please close the issue

**Closed** 2024-07-05 06:30 UTC
Labels: bug, Good issue(gssoc), level2
